{% set name = "gemgis" %}
{% set version = "1.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a3db57771505c56d2c819ab8e37699d561369046e1afa2b80582f73549b5267a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - geopandas
    - pygeos
    - python >=3.6
    - pyvista
    - rasterio

test:
  imports:
    - gemgis
    - tests

about:
  home: https://github.com/cgre-aachen/gemgis
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: GemGIS is a Python-based, open-source spatial data processing library. It is capable of preprocessing spatial data such as vector data raster data, data obtained from online services and many more data formats. GemGIS wraps and extends the functionality of packages known to the geo-community such as GeoPandas,
    Rasterio, OWSLib, Shapely, PyVista, Pandas, and NumPy.
  doc_url: https://gemgis.readthedocs.io/en/latest
  dev_url: https://github.com/cgre-aachen/gemgis

extra:
  recipe-maintainers:
    - AlexanderJuestel
