{% set name = "gemgis" %}
{% set version = "1.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/GemGIS-{{ version }}.tar.gz
  sha256: 4b993443655fe2c676239f002ff1cbc19b47e0c0d3a241adcfe08c965c876c7d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=68.1.2
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8
    - geopandas
    - rasterio
    - pyvista

test:
  imports:
    - gemgis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cgre-aachen/gemgis
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: GemGIS is a Python-based, open-source spatial data processing library. It is capable of preprocessing spatial data such as vector data raster data, data obtained from online services and many more data formats. GemGIS wraps and extends the functionality of packages known to the geo-community such as GeoPandas,
    Rasterio, OWSLib, Shapely, PyVista, Pandas, and NumPy.
  doc_url: https://gemgis.readthedocs.io/en/latest
  dev_url: https://github.com/cgre-aachen/gemgis

extra:
  recipe-maintainers:
    - AlexanderJuestel
